name: contactlist01b4a
description: Contact List v01 no back4app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter    
  # Gerenciador de estados
  get: ^4.6.1
  # Google
  google_fonts: ^2.3.1  
  # Back4app
  parse_server_sdk_flutter: ^3.1.0
  # outros
  uuid: ^3.0.6
  validatorless: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
